### Sign Up

POST http://localhost:3003/ng-cash/user/signup
Content-Type: application/json

{
    "username": "Laura",
    "password": "Casa1237"
}

### Login

POST http://localhost:3003/ng-cash/user/login
Content-Type: application/json

{
    "username": "Laura",
    "password": "Casa1237"
}

### Get Balance 

GET http://localhost:3003/ng-cash/user/balance
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc1MjA2M2VkLTIzYmQtNGNmYy05MjgxLTk5YmQ1MDU1OGRjZCIsImlhdCI6MTY2OTc2MDY3NiwiZXhwIjoxNjY5ODQ3MDc2fQ.6i5e0TZZga3_bpytoukKuVJFphD68eI97-KFiuRRCc8

### Transaction

POST http://localhost:3003/ng-cash/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZWE3ZjUyLTI0M2MtNGZhZS04Njg1LWQ5YTM4MjM1ZmMxMSIsImlhdCI6MTY2OTc2NDQ0MCwiZXhwIjoxNzU2MTY0NDQwfQ.O0bYnmPymyaEUfCYWmR_ESugJKXGY50wGW1on-7FMA4
Content-Type: application/json

{
    "username": "Pepe",
    "value": 80
}

### Get All Transactions 

GET http://localhost:3003/ng-cash/transactions/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDI1YWNhLTM0MWUtNGJiNS05NThkLWIwOWFhZTA1OGU4OCIsImlhdCI6MTY2ODk5Mjk4MCwiZXhwIjoxNjY5MDc5MzgwfQ.upmBdAuJuQiN5qHn-Q0SWY6tWq8PTNjH-k3dVxYjOPQ

### Get Filter Transactions

GET http://localhost:3003/ng-cash/transactions/filter/?sort=debit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDI1YWNhLTM0MWUtNGJiNS05NThkLWIwOWFhZTA1OGU4OCIsImlhdCI6MTY2ODk5Mjk4MCwiZXhwIjoxNjY5MDc5MzgwfQ.upmBdAuJuQiN5qHn-Q0SWY6tWq8PTNjH-k3dVxYjOPQ
